### ISSUE TITLE
lightning + wandb + ddp  how to sweep config

### ISSUE THREAD

**Issue by tobiascz** [borisdayma/lightning-kitti#3]
```
wandb.init(config=hyperparameter_defaults)
# Config parameters are automatically set by W&B sweep agent
config = wandb.config

```

This works well running only one instance of the run I think i would prefer this though.

```
wandb_logger = WandbLogger(name=hparams.name, project=hparams.project_name)
wandb_config = wandb_logger.experiment.config
```

For the multiprocessing case however there is no way to get the same wandb configs as for the previous instance as the wandb experiment only gets created if rank == 0. For rank 1 the wandb_logger.experiment is none and therfore has no config

Is there another way to use the sweep configs of wandb in combination with pytorch lightning ddp?

**Comment by borisdayma** [comment]
Hi,

Could you run 2 agents at the same time from the command line?

**Comment by tobiascz** [comment]
Thanks for your response @borisdayma. you could do this butthis would be 2 seperate runs. What i wanted to archive is to have one run with many gpus but its a bit tricky. I think this will be a future feature of wandb - I will therefore close this issue.

**Comment by rowandempster** [comment]
For future readers here's my hacky way to get the config on non-rank0 procs without starting multiple wandb runs for each proc:
```
    wandb_logger = WandbLogger(project=project, name=name, config={})
    # wandb_logger.experiment (the wandb run) is only initialized on rank0,
    # but we need every proc to get the wandb sweep config, which happens on .init
    # so we have to call .init on non rank0 procs, but we disable creating a new run
    if not isinstance(wandb_logger.experiment.config, dict):
        wandb.init(config={}, mode="disabled")
    assert isinstance(wandb.config, dict)
```
